"""Phase 4, Step 4: employment-weighted exposure quintile cutoffs (preregistration Section 5).

Cutoffs are fixed on employment of wage and salary workers ages 22-64 in the Section 5
window (2015-01 to 2020-02) and never recomputed with post-treatment data: only rows inside
that window enter the calculation.

Cutoff k (k = 1..4) is the smallest occupation score at which cumulative weighted employment,
ranked by score, reaches k/5. An occupation with score <= cutoff 1 is Q1, <= cutoff 2 is Q2,
and so on. Occupations are not split, so each quintile holds about, not exactly, 20%.
Occupations without a score (coverage report) get no quintile.

Run from the repo root:  python -m src.crosswalks.exposure_quintiles
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from src.crosswalks.occupation_exposure import employment_by_occ
from src.utils.config import REPO_ROOT, load_settings

N = 5   # quintiles, Section 5
CUTOFF_FILE = REPO_ROOT / "results" / "tables" / "exposure_quintile_cutoffs.csv"
REPORT_FILE = REPO_ROOT / "results" / "tables" / "exposure_quintiles.md"


def cutoffs(score: pd.Series, weight: pd.Series, n: int = N) -> list[float]:
    order = np.argsort(score.to_numpy(), kind="stable")
    s, cum = score.to_numpy()[order], np.cumsum(weight.to_numpy()[order]) / weight.sum()
    return [float(s[np.searchsorted(cum, k / n - 1e-12)]) for k in range(1, n)]


def assign(score: pd.Series, cuts: list[float]) -> pd.Series:
    return pd.Series(np.searchsorted(cuts, score.to_numpy(), side="left") + 1, index=score.index)


def main() -> None:
    interim = load_settings()["paths"]["interim"]
    occ = pd.read_parquet(interim / "occ2010_exposure.parquet").dropna(subset=["exposure"])
    emp = employment_by_occ()
    win = emp[emp.cutoff].merge(occ[["occ2010", "exposure"]], on="occ2010")   # scored, in window only

    cuts = cutoffs(win["exposure"], win["w"])
    occ["quintile"] = assign(occ["exposure"], cuts)
    win["quintile"] = assign(win["exposure"], cuts)
    occ[["occ2010", "exposure", "quintile"]].to_parquet(interim / "occ2010_quintile.parquet", index=False)

    pd.DataFrame({"cutoff": range(1, N), "upper_bound_inclusive": cuts}).to_csv(CUTOFF_FILE, index=False)
    share = win.groupby("quintile")["w"].sum() / win["w"].sum()
    n_occ = win.groupby("quintile")["occ2010"].nunique()
    outside = sorted((set(occ.occ2010) - set(win.occ2010)) & set(emp.occ2010))
    lines = [
        "# Exposure quintiles (Phase 4, step 4)",
        "",
        "Generated by `python -m src.crosswalks.exposure_quintiles`. Cutoffs fixed on weighted",
        "employment (WTFINL) of employed wage and salary workers ages 22-64, 2015-01 to 2020-02,",
        "scored occupations only (Section 5). Pre-period construction only: no ages, no outcomes,",
        "nothing after 2020-02.",
        "",
        "| Quintile | Exposure range (`dv_rating_beta`, OCC2010 mean) | OCC2010 codes | Share of window employment |",
        "|---|---|---|---|",
    ]
    bounds = [-np.inf, *cuts, np.inf]
    for q in range(1, N + 1):
        lo = "min" if q == 1 else f"> {bounds[q - 1]:.4f}"
        hi = "max" if q == N else f"<= {bounds[q]:.4f}"
        lines.append(f"| Q{q} | {lo} to {hi} | {n_occ.get(q, 0)} | {share.get(q, 0):.2%} |")
    lines += ["", f"Scored OCC2010 codes employed after the window but not inside it: "
              f"{', '.join(f'{c:04d}' for c in outside) or 'none'} (assigned with the same fixed cutoffs).", ""]
    REPORT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
