"""Phase 4, Step 4: employment-weighted exposure quintile cutoffs (preregistration Section 5).

Cutoffs are fixed on employment of wage and salary workers ages 22-64 in the Section 5
window (2015-01 to 2020-02) and never recomputed with post-treatment data: only rows inside
that window enter the calculation.

Cutoff k (k = 1..4) is the smallest occupation score at which cumulative weighted employment,
ranked by score, reaches k/5. An occupation with score <= cutoff 1 is Q1, <= cutoff 2 is Q2,
and so on. Occupations are not split, so each quintile holds about, not exactly, 20%.
Occupations without a score (coverage report) get no quintile.

Run from the repo root:  python -m src.crosswalks.exposure_quintiles
"""
from __future__ import annotations

import numpy as np
import pandas as pd
from ipumspy import readers

from src.crosswalks.occupation_exposure import employment_by_occ
from src.data.convert_to_parquet import locate_files
from src.data.inspect_codes import labels_for
from src.data.ipums_extract import load_log
from src.utils.config import REPO_ROOT, load_settings

N = 5   # quintiles, Section 5
CUTOFF_FILE = REPO_ROOT / "results" / "tables" / "exposure_quintile_cutoffs.csv"
REPORT_FILE = REPO_ROOT / "results" / "tables" / "exposure_quintiles.md"


def cutoffs(score: pd.Series, weight: pd.Series, n: int = N) -> list[float]:
    order = np.argsort(score.to_numpy(), kind="stable")
    s, cum = score.to_numpy()[order], np.cumsum(weight.to_numpy()[order]) / weight.sum()
    return [float(s[np.searchsorted(cum, k / n - 1e-12)]) for k in range(1, n)]


def assign(score: pd.Series, cuts: list[float]) -> pd.Series:
    return pd.Series(np.searchsorted(cuts, score.to_numpy(), side="left") + 1, index=score.index)


def load_cutoffs() -> list[float]:
    """The frozen cutoffs. Every later stage reads these; nothing recomputes them."""
    return pd.read_csv(CUTOFF_FILE)["upper_bound_inclusive"].tolist()


def occupation_quintiles() -> pd.DataFrame:
    """occ2010, exposure, quintile for every scored occupation, from the frozen cutoffs."""
    occ = pd.read_parquet(load_settings()["paths"]["interim"] / "occ2010_exposure.parquet")
    occ = occ.dropna(subset=["exposure"])[["occ2010", "exposure"]]
    occ["quintile"] = assign(occ["exposure"], load_cutoffs())
    return occ


def main() -> None:
    occ = pd.read_parquet(load_settings()["paths"]["interim"] / "occ2010_exposure.parquet")
    occ = occ.dropna(subset=["exposure"])
    emp = employment_by_occ()
    win = emp[emp.cutoff].merge(occ[["occ2010", "exposure"]], on="occ2010")   # scored, in window only

    cuts = cutoffs(win["exposure"], win["w"])
    if CUTOFF_FILE.exists():   # frozen: verify, never overwrite
        if not np.allclose(cuts, load_cutoffs(), rtol=0, atol=1e-12):
            raise RuntimeError(f"Recomputed cutoffs {cuts} differ from frozen {CUTOFF_FILE}. "
                               "Inputs changed; resolve before any later stage runs.")
        print(f"Cutoffs match frozen {CUTOFF_FILE.relative_to(REPO_ROOT)}")
    else:
        pd.DataFrame({"cutoff": range(1, N), "upper_bound_inclusive": cuts}).to_csv(CUTOFF_FILE, index=False)
    occ["quintile"] = assign(occ["exposure"], cuts)
    win["quintile"] = assign(win["exposure"], cuts)

    share = win.groupby("quintile")["w"].sum() / win["w"].sum()
    n_occ = win.groupby("quintile")["occ2010"].nunique()
    outside = sorted((set(occ.occ2010) - set(win.occ2010)) & set(emp.occ2010))
    lines = [
        "# Exposure quintiles (Phase 4, step 4)",
        "",
        "Generated by `python -m src.crosswalks.exposure_quintiles`. Cutoffs fixed on weighted",
        "employment (WTFINL) of employed wage and salary workers ages 22-64, 2015-01 to 2020-02,",
        "scored occupations only (Section 5). Pre-period construction only: no ages, no outcomes,",
        "nothing after 2020-02.",
        "",
        "| Quintile | Exposure range (`dv_rating_beta`, OCC2010 mean) | OCC2010 codes | Share of window employment |",
        "|---|---|---|---|",
    ]
    bounds = [-np.inf, *cuts, np.inf]
    for q in range(1, N + 1):
        lo = "min" if q == 1 else f"> {bounds[q - 1]:.4f}"
        hi = "max" if q == N else f"<= {bounds[q]:.4f}"
        lines.append(f"| Q{q} | {lo} to {hi} | {n_occ.get(q, 0)} | {share.get(q, 0):.2%} |")
    lines += ["", f"Scored OCC2010 codes employed after the window but not inside it: "
              f"{', '.join(f'{c:04d}' for c in outside) or 'none'} (assigned with the same fixed cutoffs).", ""]

    # Face-validity check: the largest occupations at each end of the exposure scale.
    labels = labels_for(readers.read_ipums_ddi(locate_files(load_log())[2]), "OCC2010")
    win["share_q"] = win["w"] / win.groupby("quintile")["w"].transform("sum")
    for q in (N, 1):
        lines += [f"## Ten largest occupations in Q{q} (window employment)", "",
                  "| OCC2010 | IPUMS label | Exposure | Share of Q employment |", "|---|---|---|---|"]
        for r in win[win.quintile == q].nlargest(10, "w").itertuples():
            lines.append(f"| {r.occ2010:04d} | {labels.get(r.occ2010, '')} | {r.exposure:.3f} | {r.share_q:.1%} |")
        lines.append("")
    REPORT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
