"""Phase 5, Step 3: minimum detectable effect for the headline (preregistration Section 16).

Method (set by Aryan, 2026-10-04): fit the Section 8 Poisson model on the pre-period window
2015-01 to 2020-02 with a fake treatment date of 2016-12, standard errors clustered by
occupation, and take MDE = 2.80 x SE (5% two-sided, 80% power). Only standard errors leave
this module; coefficients are never read, printed or saved.

Section 8 sample: ages 22-25, 26-34 (treated, secondary) and 35-49 (reference). The 50-64
group belongs to the separate placebo model (Section 12) and is not in this fit. Survey
weights enter through the outcome (weighted counts), not as regression weights.

Run from the repo root:  python -m src.analysis.mde
"""
from __future__ import annotations

import math

import pandas as pd
import pyfixest as pf

from src.utils.config import REPO_ROOT, load_settings

WINDOW = (201501, 202002)        # Section 5 / 16 pre-period
FAKE_TREATMENT = 201612          # Aryan, 2026-10-04: avoids the placebo dates 2017-12 and 2018-12
Z = 1.96 + 0.84                  # 5% two-sided, 80% power -> 2.80
AGES = ["22-25", "26-34", "35-49"]
REPORT_FILE = REPO_ROOT / "results" / "tables" / "mde.md"


def main() -> None:
    s = load_settings()
    p = pd.read_parquet(s["paths"]["processed"] / "panel_occ_age_month.parquet",
                        columns=["occ2010", "age_group", "ym", "quintile", "emp_w"])
    p = p[p.ym.between(*WINDOW) & p.age_group.isin(AGES)].copy()
    post = (p.ym >= FAKE_TREATMENT).astype(int)
    terms = []
    for q in (2, 3, 4, 5):
        for a in ("22-25", "26-34"):
            name = f"q{q}_a{a[:2]}"
            p[name] = ((p.quintile == q) & (p.age_group == a)).astype(int) * post
            terms.append(name)

    fit = pf.fepois(f"emp_w ~ {' + '.join(terms)} | occ2010^age_group + occ2010^ym + age_group^ym",
                    data=p, vcov={"CRV1": "occ2010"})
    se = fit.se()   # standard errors only
    n_obs, n_clusters = fit._N, fit._G[0]

    lines = [
        "# Minimum detectable effect (Phase 5; preregistration Section 16)",
        "",
        "Generated by `python -m src.analysis.mde`. Section 8 Poisson model (pyfixest `fepois`,",
        "fixed effects occupation x age, occupation x month, age x month), fitted on",
        f"{WINDOW[0] // 100}-{WINDOW[0] % 100:02d} to {WINDOW[1] // 100}-{WINDOW[1] % 100:02d} only, "
        f"fake treatment {FAKE_TREATMENT // 100}-{FAKE_TREATMENT % 100:02d}, standard errors clustered by occupation.",
        f"MDE = {Z:.2f} x SE (5% two-sided, 80% power). Coefficients are not computed into this report.",
        f"Observations used: {n_obs:,}; occupation clusters: {n_clusters}.",
        "",
        "Caveats. The fake design has 62 months (23 fake-pre, 39 fake-post); the real main sample has",
        "117 (73 pre, 44 post). Fewer months and a short pre-period make this SE larger, so on that",
        "count the MDE is conservative. Working the other way: CPS monthly samples were about",
        "25-35% larger in 2015-2020 than after 2022 (design_notes.md, 2026-09-21), so the real",
        "post-period cells are thinner than these. The net direction is not known; treat this as",
        "a guide to the order of magnitude, not a precise power figure.",
        "",
        "| Term | Age group | Quintile | SE (log points) | MDE (log points) | Detectable decline | Detectable increase |",
        "|---|---|---|---|---|---|---|",
    ]
    for t in terms:
        q, a = t[1], t.split("_a")[1]
        m = Z * se[t]
        head = " **(headline)**" if t == "q5_a22" else ""
        lines.append(f"| `{t}`{head} | {a}-{'25' if a == '22' else '34'} | Q{q} | {se[t]:.4f} | {m:.4f} | "
                     f"{1 - math.exp(-m):.1%} | {math.exp(m) - 1:.1%} |")
    lines += ["", "Detectable decline = 1 - exp(-MDE); detectable increase = exp(MDE) - 1. Each is",
              "relative to Q1 and to ages 35-49 (the Section 8 reference groups).", ""]
    REPORT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
